apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  namespace: staging
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: my-app
        image: vyshnavipriya/my-app:latest
        ports:
        - containerPort: 3000
